### ISSUE TITLE
Issue with raop.c

### ISSUE THREAD

**Issue by Noscar06** [FDH2/UxPlay#477]
I'm trying to build it on my windows 11 pc but it doesnt work, it used to always work with me but it suddenly broke on my pc, when i tried to install a newer version(1.73, was in 1.72), while building I get the following error:
```
$ ninja
[1/4] Building C object lib/CMakeFiles/airplay.dir/raop.c.obj
FAILED: lib/CMakeFiles/airplay.dir/raop.c.obj
C:\msys64\mingw64\bin\cc.exe -DNOHOLD -DOPENSSL_API_COMPAT=0x10101000L -DPLIST_230 -ID:/UxPlay/lib/playfair -ID:/UxPlay/lib/llhttp -I"C:/Program Files/Bonjour SDK/Include" -DSTANDALONE -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -DTARGET_POSIX -D_WIN32 -fPIC -DPIC -D_REENTRANT -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Wall -Ofast -march=native -MD -MT lib/CMakeFiles/airplay.dir/raop.c.obj -MF lib\CMakeFiles\airplay.dir\raop.c.obj.d -o lib/CMakeFiles/airplay.dir/raop.c.obj -c D:/UxPlay/lib/raop.c
D:/UxPlay/lib/raop.c: In function 'plist_mem_free_wrapper':
D:/UxPlay/lib/raop.c:41:25: error: 'plst_ptr' undeclared (first use in this function); did you mean 'plist_ptr'?
   41 |         plist_mem_free (plst_ptr);
      |                         ^~~~~~~~
      |                         plist_ptr
D:/UxPlay/lib/raop.c:41:25: note: each undeclared identifier is reported only once for each function it appears in
ninja: build stopped: subcommand failed.
```

**Comment by fduncanh** [comment]
thanks for reporting.  fixed now.

A recent commit yesterday  had this typo: a small change  wasn't properly tested before the commit.

**Comment by Noscar06** [comment]
unfortunately im still experiencing the same issue... even after updating to the new raop files

**Comment by fduncanh** [comment]
Did you pull directly from github?

github master branch lines of raop.c starting at line 37 should read as below:

(commit 7ebd818  )

```
/* libplist-2.3.0  API change */
#ifndef PLIST_230
static void plist_mem_free(void *ptr) {
    if (ptr) {
        free (ptr);
    }
}
#endif



```
do "git pull --rebase"  in an existing clone, but its cleaner to just delete it and do a new clone

**Comment by Noscar06** [comment]
When I posted my earlier commend I had already installed a new clone. However, I have just tried again and it worked perfectly fine now. Thank you for looking into this issue.
