### ISSUE TITLE
renderers/audio_renderer_gstreamer.c:22:10: fatal error: 'gst/gst.h' file not found

### ISSUE THREAD

**Issue by satoshinotdead** [FDH2/UxPlay#96]
I tried to install PKGs and brew different Gstreamer (following README.MD) but stills no working.

I'm building on MacOS Monterrey.

`Mac UxPlay % make [ 18%] Built target playfair [ 30%] Built target llhttp [ 84%] Built target airplay [ 87%] Building C object renderers/CMakeFiles/renderers.dir/audio_renderer_gstreamer.c.o /Users/$USER/UxPlay/renderers/audio_renderer_gstreamer.c:22:10: fatal error: 'gst/gst.h' file not found #include <gst/gst.h> ^~~~~~~~~~~ 1 error generated. make[2]: *** [renderers/CMakeFiles/renderers.dir/audio_renderer_gstreamer.c.o] Error 1 make[1]: *** [renderers/CMakeFiles/renderers.dir/all] Error 2`

I've installed on Debian with sucess (ATI weird propietary drivers problem but nothing with UxPlay)

Thanks for your time :)

**Comment by fduncanh** [comment]
The build on Monterey was tested  using the "official" gstreamer-1.20.1  package from http://gstreamer.freedesktop.org .
I recomend using that unless you need gstreamer with other homebrew packages.
(a build with homebrew was tested earlier on Catalina)


I dont have Monterey available now  but I will test that the build with brew on Catalina still works

**Comment by fduncanh** [comment]
I am also seeing the gst/gst.h issue.

There are some issues in the recent macOS builds of gstreamer  connected to  "rpath" that is messing up the include paths

I will need to find the fix.   I'll get back to you.  may take a day or two.

**Comment by satoshinotdead** [comment]
Thanks, I recieved another reply with that:

> I reproduced your issue.   I found it's because of changes in the GStreamer for mac build.     it now needs pkg-config to be run with --define-prefix option  in CMakeList.txt in directory renderers,  when cmake is run,     I'll fix this  in the next day or two, hopefully.

I'm on Intel and I'm not a dev but I can test if you have something 🤙

**Comment by fduncanh** [comment]
If you are on intel, you can use the gstreamer official package  Gstreamer 1.18  instead of brew.

The issue is because of packaging changes in 1.20 to accommodate M1 macs.

**Comment by fduncanh** [comment]
Its fixed now (simple fix).

If you use Brew for GStreamer, you probably need to 
```
export GST_PLUGINS_PATH=/usr/local/lib/gstreamer-1.0
```

before running uxplay (I had to).  If you need this, it should be set by your .bashrc or .zshrc
(I'm surprised brew didnt seem to do this automatically) 

I tested both brew and official gstreamer  (/Library/Frameworks/GStreamer.framework)
both work fine now.

**Comment by fduncanh** [comment]
closing now.  I think its fixed, but @satoshinotdead please reply here to say if it now works for you

thanks for you report  of this,

**Comment by satoshinotdead** [comment]
Hi there!Sorry but what's the official package that you are using? I tried with Brew and [that ones](https://gstreamer.freedesktop.org/download/), using the export path but still don't working here.

Thanks for your follow up.

**Comment by fduncanh** [comment]
The official package is mentioned in the README, which says:



First get the latest macOS release of GStreamer-1.0 from https://gstreamer.freedesktop.org/download/. Install both the macOS runtime and development installer packages. Assuming that the latest release is 1.20.2. install gstreamer-1.0-1.20.2-universal.pkg and gstreamer-1.0-devel-1.20.2-universal.pkg. (If you have an Intel-architecture Mac, and have problems with the "universal" packages, you can also use gstreamer-1.0-1.18.6-x86_64.pkg and gstreamer-1.0-devel-1.18.6-x86_64.pkg.) Click on them to install (they install to /Library/FrameWorks/GStreamer.framework). It is recommended you use GStreamer.framework rather than install Gstreamer with Homebrew or MacPorts (see later).

**Comment by fduncanh** [comment]
@satoshinotdead 

Please explain your problem fully:

 Which release of macOS are you using?  You said it was on an intel mac..

0.  Are you using the current github version of uxplay 1.51? 
1.  which gstreamer package have you installed ?    from where?
2.  Did **cmake** work yes/no
3. did **make** work yes/no
4.  did **sudo make install**  work yes/no
5.   if you managed to compile it, what happened when you   tried to run uxplay?

show any error messages you got here.
